name: Generate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run make generate
        run: make generate

      - name: Check for generation changes not committed to git by user
        run: |
          git diff --exit-code || (echo 'Error: Files were changed after make generate. Please run make generate and commit the results.' && exit 1)
